myacpaas eventhandler addon
digipolisantwerp/starter-kit_app_nodejs pull request #56
Opened 2021-02-08 14:08 UTC by vademo

2021-02-08 16:13 UTC, PeterBrion requested changes

2021-02-08 16:13 UTC, PeterBrion commented on backend/src/services/eventhandler.js
> +export async function sendEvent(namespace, topic, message, ownerKey) {
ownerKey kan evt. ook uit config (env var) komen.

2021-02-08 16:13 UTC, PeterBrion commented on backend/src/services/eventhandler.js
> +    debug: true,
Wat doet `debug: true`?

2021-02-08 16:13 UTC, PeterBrion commented on backend/src/services/eventhandler.js
> +  } catch (error) {
Kan dit ook zo?

```
    if (error.response) {
      logger.error('EventHandler publish failed', error.response.status, error.response.data);
    } else if (error.request) {
      logger.error('EventHandler publish failed', error.request);
    }
```
(Ben niet zeker of winston dit zo aanvaardt.)

Zonder de message 'EventHandler publish failed' en de verschillende logger calls krijg je loglijnen met enkel data of een status, die dan moeilijk aan elkaar te correleren zijn. `error.response.headers` lijkt me (zeker in het geval van de Event Handler) niet nuttig om te loggen.

2021-02-08 16:13 UTC, PeterBrion commented on backend/test/routes/eventhander.test.js
> +describe('/api/recieveEvent', () => {
De URL in de description klopt niet (maar wordt misschien nog aangepast).

2021-02-09 15:54 UTC, PeterBrion approved these changes
Nog 1 minor comment, voor de rest ok!

2021-02-09 15:54 UTC, PeterBrion commented on backend/src/controllers/events.js
> +export async function postEvent(req, res, next) {
Kan je deze controller functie nog wegdoen aangezien die niet meer wordt gebruikt?

2021-02-09 16:10 UTC, vademo commented on backend/src/routes/eventhandler.router.js
> +router.post('/', postEvent);
verwijderd

2021-02-09 16:10 UTC, merged