Feature/modules
digipolisantwerp/starter-kit_app_nodejs pull request #63
Opened 2022-01-11 08:46 UTC by vademo

2022-01-12 18:21 UTC, TriangleJuice requested changes

2022-01-12 18:21 UTC, TriangleJuice commented on .github/workflows/ci.yml.orig
> +>>>>>>> Stashed changes
Merge conflicts + I think this file should be deleted anyway.

2022-01-12 18:21 UTC, TriangleJuice commented on backend/package.json.orig
> +>>>>>>> Stashed changes
Merge conflicts + I think this file should be deleted anyway.

2022-01-13 07:37 UTC, vademo commented on .github/workflows/ci.yml.orig
> +>>>>>>> Stashed changes
deleted. indeed irrelevant

2022-01-13 07:37 UTC, vademo commented on backend/package.json.orig
> +>>>>>>> Stashed changes
deleted. indeed irrelevant

2022-01-13 09:06 UTC, TriangleJuice approved these changes

2022-01-13 11:59 UTC, jsebrech reviewed
Ik ben wel een fan van ESM notatie voor import/export, dus puur op vlak van notatie vind ik het wel aangenaam lezen zo. Ik ben ook een fan van de uitfasering van babel waar mogelijk, want the juice isn't worth the squeeze imho. Ik heb enkel wat mijn twijfels bij het gebruik van es-module-specifier-resolution binnen node en wat de potentiële nadelen van die aanpak zijn tov CommonJS / require. Wat is de reden dat je toch zou willen teruggaan naar require()?

2022-01-13 12:33 UTC, vademo commented
> Ik ben wel een fan van ESM notatie voor import/export, dus puur op vlak van notatie vind ik het wel aangenaam lezen zo. Ik ben ook een fan van de uitfasering van babel waar mogelijk, want the juice isn't worth the squeeze imho. Ik heb enkel wat mijn twijfels bij het gebruik van es-module-specifier-resolution binnen node en wat de potentiële nadelen van die aanpak zijn tov CommonJS / require. Wat is de reden dat je toch zou willen teruggaan naar require()?

es-module-specifier-resolution heb ik toegevoegd om zoveel mogelijk het babel gedrag te behouden, de extensies niet moeten toevoegen, import index file van een folder. Deze is experimental maar gaat al een aantal versies mee. Ik verwacht (hoop) dat dit stable of default behaviour wordt. Indien niet is dit ook geen ramp om op te kuisen
```javascript
 import x from './models' 
 ```
 ipv
 ```javascript
 import x from './models/index.js' 
 ```
 
 Waarom ik zou teruggaan naar requirejs
-  Ik ben absoluut geen fan van de babel setup. Dit vertraagt builds, tests, startup, We moeten de babel setup ook werkend houden. We gebruiken dit in 2022 hier enkel voor import/export te transplilen naar requirejs. Dan gebruik ik liever de native requirejs syntax
- Bij deze oefening heb ik gemerkt dat niet alles 100% compatibel is zoals bv onze coverage reporter (nyc) sommige zaken zijn lichtjes anders.
- Ik wou deze discussie opstarten

2022-01-21 14:21 UTC, merged