Setup redis helper.
digipolisantwerp/starter-kit_app_nodejs pull request #83
Opened 2023-02-16 12:05 UTC by vademo

2023-02-16 12:23 UTC, TriangleJuice requested changes

2023-02-16 12:23 UTC, TriangleJuice commented on backend/src/helpers/redis.helper.js
> +  legacyMode: true,
Waarom `legacyMode`?

2023-02-16 12:24 UTC, TriangleJuice reviewed
Eén opmerking …

2023-02-16 13:01 UTC, Jan-Bart approved these changes

2023-02-16 14:00 UTC, vademo commented on backend/src/helpers/redis.helper.js
> +  legacyMode: true,
Ik had in een project deze gebruikt voor express session + redis te gebruiken. https://www.npmjs.com/package/connect-redis
Met de laatste versie van de redis lib verwacht deze de leacyMode

2023-02-17 08:36 UTC, TriangleJuice approved these changes

2023-02-17 08:36 UTC, merged